name: Deploy da documentação

on:
  push:
    branches:
      - docs
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar credenciais do Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: astral-sh/setup-uv@v6
      - run: uv sync
      - run: uv run mkdocs gh-deploy --force
